### PR TITLE
add hostNetwork value to injector deployment

### PR DESCRIPTION
**Pull request by paulwitt**
See these:
https://github.com/hashicorp/vault-helm/issues/470
https://github.com/hashicorp/vault-k8s/issues/72

### CODE REVIEW

**Review by jasonodonnell — COMMENTED** [review]
Hi @paulwitt, this looks great! We just need a unit test for the configurable and this is ready to merge. You can find the bats unit tests in `test/unit`. Please let me know if you have any questions!

**Comment by paulwitt** [comment]
@jasonodonnell done.  Thanks!

**Comment by Domwa** [comment]
Hello - any update on this?

**Review by jasonodonnell — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
