### PR TITLE
Support for ingress

### PR DESCRIPTION
**Pull request by mogaal**
Hello, 

Within my actual implementation I have to expose the Vault UI. For that, I had to add ingress support. Sharing new feature here. 

Have a nice weekend

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Be aware this came in @Xtigyro before you go splitting your PRs.

**Comment by jasonodonnell** [comment]
Hi @mogaal, thanks for the contribution!

This is a great feature which we would like to add.  Can you add tests for this?  You can find all the tests in `test/unit`.

**Comment by Xtigyro** [comment]
@jasonodonnell This implementation differs quite a bit in some ways. We should consider the pros and cons of the two.

**Comment by mogaal** [comment]
@jasonodonnell Just added units tests. To be honest I followed the most common approach in almost all helm charts you find in [stable/*](https://github.com/helm/charts/tree/master/stable) for ingress set up. 

Having a look to @Xtigyro's implementation I personally would take away SSL management out of the helm chart. You already have custom charts implementations like [certmanager/lets-encrypt](https://github.com/jetstack/cert-manager) which are specifically for that and they work great.

**Comment by billimek** [comment]
Agree with @mogaal on both points here. IMO the chart ingress should follow the pattern employed by other helm charts.

**Comment by Xtigyro** [comment]
@mogaal @billimek The Ingress implementation is independent from the TLS stuff. Re the Ingress - I combined the general approach with some simplification if you want to use `NGINX` - which most people do.

**Comment by catsby** [comment]
Thank you @mogaal for the contribution! And thank you everyone who participated in civil discussion here.

**Pull request merged**
