### PR TITLE
Add TLS support 

### PR DESCRIPTION
**Pull request by anhdat**
- Add TLS support for health check: with TLS enabled, health check also need to use `https` scheme
- Add custom NodePort: in the situation of using NodePort type for Service, user should be able to define selected NodePort

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Hey @anhdat, thanks for another contribution!

This was something that I was working on myself, appreciate you doing this.  This did cause a failure in the acceptance tests.  Since the default Vault config disables TLS (because there is no TLS bootstrapping as part of the helm install), I think we will need to make `tls_disable: true` by default.

**Comment by jasonodonnell** [comment]
@anhdat #23 reduced the complexity of the UI service by using 8200.  The Vault server will handle either http/https connections depending on the configuration.

Given this change, I would suggest making just a single variable for specifying `nodePort`.

**Comment by anhdat** [comment]
@jasonodonnell got it. I will update for both remarks :+1:

**Comment by anhdat** [comment]
@jasonodonnell the acceptance tests are passing now, please proceed the review.

**Comment by jasonodonnell** [comment]
@anhdat Thanks!  I have one minor request, can we turn `tls_disable` into `tlsDisable` just to be consistent with the rest of the options (we've been using camel case).

Besides that minor feedback this LGTM!

**Comment by anhdat** [comment]
>can we turn tls_disable into tlsDisable just to be consistent with the rest of the options (we've been using camel case)?

Absolutely, I missed that. Updated now :ok_hand:

**Pull request merged**
