### PR TITLE
support extraLabels for vault-agent-injector

### PR DESCRIPTION
**Pull request by logileifs**
fixes issue https://github.com/hashicorp/vault-helm/issues/427

### CODE REVIEW

**Review by jasonodonnell — COMMENTED** [review]
Hi @logileifs, thanks for the contribution!

This looks good but will require unit tests to make sure the configurable works and has coverage. Would you mind adding some? You can find the `bats` injector unit tests here: https://github.com/hashicorp/vault-helm/blob/master/test/unit/injector-deployment.bats.

Here's a test that's equivalent: https://github.com/hashicorp/vault-helm/blob/master/test/unit/server-statefulset.bats#L891-L901.

**Comment by jasonodonnell** [comment]
@logileifs Also the CLA will need to be signed 😄

**Comment by logileifs** [comment]
Hey @jasonodonnell thanks for the tips, I added a test for the extraLabels on the injector and I have already signed the CLA, I don't know why it's not updating 😕

**Comment by logileifs** [comment]
Screenshot 2020-12-07 at 15 57 29

It's already signed but when I click recheck, nothing happens

**Review by jasonodonnell — COMMENTED** [review]
One last change, this needs to be added to the `values.yaml` file. You can set it to blank just we like we do for `server`:

```yaml
injector:
  ...
  extraLabels: {}
```

**Review by jasonodonnell — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by logileifs** [comment]
Thanks for the quick response @jasonodonnell and just out of curiosity, when can I expect to see this change in a release?

**Comment by jasonodonnell** [comment]
We release monthly (if there's things to be released) on the third Tuesday, so good chance you'll see it then.

**Pull request merged**
