### PR TITLE
Add support for nodePort for `vault-active` and `vault-standby` services

### PR DESCRIPTION
**Pull request by jzck**
When using `ha.enabled = true` and `service.nodePort = 30001` in conjunction, the ports clash because it can only be allocated to a single service (`vault`), therefore it can't also be allocated to the `vault-active` and `vault-standby` service:

```
Error: cannot patch "vault-standby" with kind Service: Service "vault-standby" is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated && cannot patch "vault" with kind Service: Service "vault" is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated
```

### CODE REVIEW

**Comment by jzck** [comment]
FYI, this PR is addressing the same issue as: https://github.com/hashicorp/vault-helm/pull/463.

Except here we define customizable `nodePort`s for each service instead of doing random, as suggested by https://github.com/hashicorp/vault-helm/pull/463 (cc @jasonodonnell )

**Review by samgabrail — APPROVED** [review]
Looks good to me.

**Review by gsanchez-uz — APPROVED** [review]
I changed same code for resolve this issue on my clusters

**Review by srosell-uz — APPROVED** [review]

**Review by gsanchez-uz — APPROVED** [review]

**Review by gsanchez-uz — APPROVED** [review]

**Review by swenson — APPROVED** [review]
Thanks for this.

This slightly breaks backwards compatibility I think, since we don't fall back to the `.Values.server.service.nodePort`. However, I think that would just keep the buggy behavior, which we don't want.

So, I think we should go ahead and go forward with merging this.

**Pull request merged**
