### PR TITLE
Add AWS credential environment variable

### PR DESCRIPTION
**Pull request by anhdat**
This PR allows user to add AWS credential via environment variable with a Kubernetes Secret object:

```yaml
# values
server:
  aws:
    secretName: vault
    secretKey: AWS_SECRET_ACCESS_KEY
  extraEnvironmentVars:
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: xxx
```

Secret object:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: xxx
```

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Hi @anhdat, thanks for the contribution!

This is already possible using the Chart as is (but in a more generic way that isn't specific to AWS):

```yaml
server:
   extraVolumes:
     - type: secret
       name:  vault
   extraEnvironmentVars:
     AWS_REGION: eu-west-1
     AWS_ACCESS_KEY_ID: xxx
```

Can you provide some additional context on why we should add an AWS specific option?

**Comment by anhdat** [comment]
hi @jasonodonnell, thanks for fast response. 

Not sure how `extraVolumes` will work since it would be mounted as a file at `mountPath: /vault/userconfig/{{ .name }}` while we want an environment variable or able to mount a file at `~/.aws/credentials`. 

I don't know what should be the standard way to do this in HashiCorp's charts, in many charts we usually allow users to freely pass the env vars configuration (e.g. https://github.com/helm/charts/blob/master/stable/cert-manager/templates/deployment.yaml#L58). I guess that HashiCorp charts want to restrict which mount point should be used and limit on names in env var. So I followed the approach in `consul-helm` https://github.com/hashicorp/consul-helm/blob/master/templates/enterprise-license.yaml#L40

Let me know if I misunderstood this. Thanks.

**Comment by anhdat** [comment]
hi @jasonodonnell do we have any update on this? Thanks.

**Comment by jasonodonnell** [comment]
@anhdat,

I'd still like this to be not AWS specific.  I think this could be done with the following:

Update helper (add `mountPath`)
```
{{/*
Set's which additional volumes should be mounted to the container
based on the mode configured.
*/}}
{{- define "vault.mounts" -}}
  {{ if eq .mode "standalone" }}
    {{ if eq (.Values.server.auditStorage.enabled | toString) "true" }}
            - name: audit
              mountPath: /vault/audit
    {{ end }}
    {{ if eq (.Values.server.dataStorage.enabled | toString) "true" }}
            - name: data
              mountPath: /vault/data
    {{ end }}
  {{ end }}
  {{ if and (ne .mode "dev") (or (ne .Values.server.standalone.config "")  (ne .Values.server.ha.config "")) }}
            - name: config
              mountPath: /vault/config
  {{ end }}
  {{- range .Values.server.extraVolumes }}
            - name: userconfig-{{ .name }}
              readOnly: true
              mountPath: {{ .path | default "/vault/userconfig" }}/{{ .name }}
  {{- end }}
{{- end -}}
```

New helper: _extraSecretEnvironmentVars_
```
{{/*
Inject extra environment populated by secrets, if populated
*/}}
{{- define "vault.extraSecretEnvironmentVars" -}}
{{- if .extraSecretEnvironmentVars -}}
{{- range .extraSecretEnvironmentVars }}
- name: {{ .envName }}
  valueFrom:
   secretKeyRef:
     name: {{ .secretName }}
     key: {{ .secretKey }}
{{- end -}}
{{- end -}}
{{- end -}}
```

Thoughts?

**Comment by anhdat** [comment]
I like the generic approach more. :+1: 
Your comment is almost a complete PR, we still need tests for that.
Will you open a new PR yourself or should I update this PR?

**Comment by jasonodonnell** [comment]
I can add this in a new PR later this week, however, if you want this sooner (and the contribution) you can update the PR. :)

**Comment by anhdat** [comment]
I'm using this chart for my company deployment, managing many branches at the same time is not so nice, so I will submit another PR today. Thanks for the guidance.

**Comment by anhdat** [comment]
Close in favor of generic approach in #16

**Pull request closed without merging**
