### PR TITLE
feat: Allow networking.k8s.io/v1

### PR DESCRIPTION
**Pull request by dirtycajunrice**
allows for the newest networking stable api

### CODE REVIEW

**Comment by philomory** [comment]
I would love to see this merged and released, is that likely to happen soon?

**Comment by DirtyCajunRice** [comment]
@philomory Was actually 1 small bug. Fixed now... but not sure who to ping to move it along.

**Comment by Kerwood** [comment]
Can we get this one going ? It is much needed.

The unit test fail because the test is using `v1beta1` logic on a `v1` manifest.
This is the unit test that fails: https://github.com/hashicorp/vault-helm/blob/master/test/unit/server-ingress.bats#L46

As you can see in below screenshot from the failed test, the api version is  `v1beta1` but the `paths` array is `v1`. Therefore, the test `yq  -r '.spec.rules[0].http.paths[0].backend.serviceName  | length > 0'` will fail.
image


I am not sure how the unit test distinguishes between the different versions or if it is possible ?

**Comment by tvoran** [comment]
Thanks for the work here! It looks like this has been addressed in https://github.com/hashicorp/vault-helm/pull/310 and https://github.com/hashicorp/vault-helm/pull/634, so I'll close this for now.

**Pull request closed without merging**
