### PR TITLE
Add support for Helm 3 in tests

### PR DESCRIPTION
**Pull request by mbrancato**
There are some syntax changes and some slight behavior changes in the Helm 3 cli. This PR adds support for these.

### CODE REVIEW

**Comment by jasonodonnell** [comment]
@mbrancato This has conflicts, can you resolve them?

**Comment by mbrancato** [comment]
Hi @jasonodonnell - I rebased this and updated the new tests that were in conflict.

**Comment by jasonodonnell** [comment]
Sorry @mbrancato, we got busy here :)

I think we are ready to review this, can you rebase this one more time?

**Comment by tvoran** [comment]
Thanks for the contribution! We've decided to continue this in another PR.

Superseded by #195

**Pull request closed without merging**
