### PR TITLE
Use github as helm repository for your chart

### PR DESCRIPTION
**Pull request by obeyler**
This PR is to give your helm chart vault as a precompiled helm.
It's easy to use gitlab as helm repository.

To do that just enable into your github repository the github page.  Like I do on our fork
You can do it by Github menu /setting 
image

image

this will serve as static page your repository, so on it also plublish the /charts/index.yaml and the chart release.
To publish a new release you just have to git clone your repo. 
```
cd charts
helm package ../.   ## this will create the vault helm chart 
helm repo index .           ## this will update the index.yaml file 
git add -m "new version" index.yaml vault-XX.XX.XX.tgz
git push
```

If you want to test it you can do:
```
helm repo add vault https://orange-cloudfoundry.github.io/vault-helm/charts/
helm install vault/vault
```

### CODE REVIEW

**Comment by billimek** [comment]
Thanks for doing this!

I wonder if we could also leverage this PR to add the necessary automation (github actions perhaps?) to automatically package and publish images so that manual steps aren't needed?

**Comment by obeyler** [comment]
maybe but I'm not familiar enough with github to do the automatic actions maybe to put in the integration chain that builds or publish the release ;-)

**Comment by jasonodonnell** [comment]
Hi @obeyler, we're considering doing this.  No decision has been made yet and we will let you know.  Thanks!

**Comment by jasonodonnell** [comment]
Hi @obeyler, we decided that we are launching an official helm repo hosted by Hashi which should be available soon. Thanks for this but closing this request.

**Pull request closed without merging**
