### PR TITLE
Remove readOnlyRootFilesystem from securityContext

### PR DESCRIPTION
**Pull request by charlieegan3**
This is a psp restriction rather than something we set here.

### CODE REVIEW

**Comment by jasonodonnell** [comment]
@charlieegan3 Thanks for the contribution!

I think we should make this configurable with a default of `true`.  Thoughts?

**Comment by charlieegan3** [comment]
Hmm, I got an error from this when applying which I've now lost to my terminal history. I was confused as it wasn't in kubectl explain.

```sh
$ kubectl explain pod.spec.securityContext.readOnlyRootFilesystem
error: field "readOnlyRootFilesystem" does not exist
```

I'll close this for now and reopen once I've had a look into it. Sorry for confusion.

**Comment by jemc** [comment]
This should have been merged instead of closed. See my comment in #93.

**Comment by malnick** [comment]
@jemc See my response on #91 and lets keep the convo in that thread, thanks again for the pointers here.

**Pull request closed without merging**
