### PR TITLE
Fix for the var declaration in server-ingress and server-route templates

### PR DESCRIPTION
**Pull request by gkarthiks**
This PR is to fix the templates issue in the server-ingress and server-route with the syntax issue.

Refers: https://github.com/hashicorp/vault-helm/issues/356

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Hi @gkarthiks, thanks for the contribution!

One of the unit tests broke in this PR:

```
not ok 207 server/route: OpenShift - route points to active service by when HA
# (in test file test/unit/server-route.bats, line 115)
#   `[ "${actual}" = "RELEASE-NAME-vault-active" ]' failed
# RELEASE-NAME-vault
# /templates/server-route.yaml
# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: RELEASE-NAME-vault
#   labels:
#     helm.sh/chart: vault-0.6.0
#     app.kubernetes.io/name: vault
#     app.kubernetes.io/instance: RELEASE-NAME
#     app.kubernetes.io/managed-by: Helm
# spec:
#   host: chart-example.local
#   to:
#     kind: Service
#     name: RELEASE-NAME-vault
#     weight: 100
#   port:
#     targetPort: 8200
#   tls:
#     termination: passthrough
```

Can you take a look at this test @gkarthiks ?

**Comment by tvoran** [comment]
Hi @gkarthiks, what version of helm are you using? I think this was an issue that is fixed in newer versions of helm, though I don't recall the exact version numbers: https://github.com/hashicorp/vault-helm/pull/270#discussion_r431285618

**Comment by gkarthiks** [comment]
@tvoran Ahh. I guess the it was because I was using the helm 2.x version?

**Comment by tvoran** [comment]
@gkarthiks That's probably it! This chart only supports helm 3.

**Pull request closed without merging**
