### PR TITLE
Add support for priorityClassName

### PR DESCRIPTION
**Pull request by bycEEE**

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Bump

**Comment by bycEEE** [comment]
Hey, thanks for the bump. Missed the notification for your previous comment.

Added unit tests.

**Comment by bycEEE** [comment]
Resolved new merge conflict, also bump @jasonodonnell.

**Comment by InAnimaTe** [comment]
@bycEEE can you fix the new merge conflict and ping approvers again? Would love to see this get added and its so close!

**Comment by bycEEE** [comment]
@InAnimaTe fixed!

**Comment by InAnimaTe** [comment]
> @InAnimaTe fixed!

Awesome, you da man! @jasonodonnell I think this is ready to go in!!

**Comment by jasonodonnell** [comment]
I didn't notice that a colleague merged a similar feature implementing priorityClassName's on the pods, so this caused a collision.  I reverted this merge, however, this feature has been implemented and merged.  You can find this in the next vault-helm release.

Thanks!

**Pull request merged**
